name: Build on MacOS

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                required: true

jobs:
    build:
        runs-on: macos-latest
        steps:

          - name: Checkout BGFX
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bgfx
                path: bgfx
        
          - name: Checkout BX
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bx
                path: bx

          - name: Checkout BIMG
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bimg
                path: bimg

          - name: Build MacOS x64
            shell: bash
            run: |
                cd bgfx
                ../bx/tools/bin/darwin/genie --with-tools --gcc=linux-gcc --platform=x64 ninja
                cd .build/projects/ninja-linux-gcc
                ninja -C debug64 bgfx bimg bx
                ninja -C release64 bgfx bimg bx shaderc

          - name: Build MacOS arm64
            shell: bash
            run: |
                cd bgfx
                ../bx/tools/bin/darwin/genie --with-tools --gcc=linux-arm-gcc --platform=ARM64 ninja
                cd .build/projects/ninja-linux-arm-gcc
                ninja -C debug64 bgfx bimg bx
                ninja -C release64 bgfx bimg bx shaderc

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: bgfx_macos
                path: |
                    *.7z
                retention-days: 7