name: Build on MacOS

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                required: true

jobs:
    build:
        runs-on: macos-latest
        steps:

          - name: Checkout BGFX
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bgfx
                path: bgfx
        
          - name: Checkout BX
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bx
                path: bx

          - name: Checkout BIMG
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bimg
                path: bimg

          - name: Build MacOS x64
            shell: bash
            run: |
                cd bgfx
                ../bx/tools/bin/darwin/genie --with-tools --platform=x64 xcode15
                cd .build/projects/xcode15
                xcodebuild -project bgfx.xcodeproj -scheme bgfx -configuration Debug ARCHS=x86_64
                xcodebuild -project bx.xcodeproj -scheme bx -configuration Debug ARCHS=x86_64
                xcodebuild -project bimg.xcodeproj -scheme bimg -configuration Debug ARCHS=x86_64
                xcodebuild -project bgfx.xcodeproj -scheme bgfx -configuration Release ARCHS=x86_64
                xcodebuild -project bx.xcodeproj -scheme bx -configuration Release ARCHS=x86_64
                xcodebuild -project bimg.xcodeproj -scheme bimg -configuration Release ARCHS=x86_64
                cd ../..
                ls

          - name: Build MacOS arm64
            shell: bash
            run: |
                cd bgfx/.build/projects/xcode15
                xcodebuild -project bgfx.xcodeproj -scheme bgfx -configuration Debug ARCHS=arm64
                xcodebuild -project bx.xcodeproj -scheme bx -configuration Debug ARCHS=arm64
                xcodebuild -project bimg.xcodeproj -scheme bimg -configuration Debug ARCHS=arm64
                xcodebuild -project bgfx.xcodeproj -scheme bgfx -configuration Release ARCHS=arm64
                xcodebuild -project bx.xcodeproj -scheme bx -configuration Release ARCHS=arm64
                xcodebuild -project bimg.xcodeproj -scheme bimg -configuration Release ARCHS=arm64
                cd ../..
                ls

          - name: Compress Product
            shell: bash
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir -p temp/include
                cp -a bgfx/include/* temp/include
                cp -a bx/include/* temp/include
                cp -a bimg/include/* temp/include
                mkdir x64
                mkdir arm64
                mv bgfx/.build/linux64_gcc/bin/shadercRelease x64/shaderc
                mv bgfx/.build/linux32_arm_gcc/bin/shadercRelease arm64/shaderc
                7z a bgfx_linux_x64_debug.7z ./bgfx/.build/linux64_gcc/bin/libbgfxDebug.a ./bgfx/.build/linux64_gcc/bin/libbxDebug.a ./bgfx/.build/linux64_gcc/bin/libbimgDebug.a x64/shaderc ./temp/include VERSION.txt
                7z a bgfx_linux_x64_release.7z ./bgfx/.build/linux64_gcc/bin/libbgfxRelease.a ./bgfx/.build/linux64_gcc/bin/libbxRelease.a ./bgfx/.build/linux64_gcc/bin/libbimgRelease.a x64/shaderc ./temp/include VERSION.txt
                7z a bgfx_linux_arm64_debug.7z ./bgfx/.build/linux32_arm_gcc/bin/libbgfxDebug.a ./bgfx/.build/linux32_arm_gcc/bin/libbxDebug.a ./bgfx/.build/linux32_arm_gcc/bin/libbimgDebug.a arm64/shaderc ./temp/include VERSION.txt
                7z a bgfx_linux_arm64_release.7z ./bgfx/.build/linux32_arm_gcc/bin/libbgfxRelease.a ./bgfx/.build/linux32_arm_gcc/bin/libbxRelease.a ./bgfx/.build/linux32_arm_gcc/bin/libbimgRelease.a arm64/shaderc ./temp/include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: bgfx_macos
                path: |
                    *.7z
                retention-days: 7